# This file was generated by GoReleaser. DO NOT EDIT.
cask "kap" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "dee17cb483fee72598b39df71fbb95efe74dece5819fee4bf6b57229adac3014"
      url "https://github.com/billygate/kap-toolsbox/releases/download/v#{version}/kap-toolsbox_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c6fdcc9652653674d8a196d1c32991778e1fedc26c31d7e99b890e724aa4b45d"
      url "https://github.com/billygate/kap-toolsbox/releases/download/v#{version}/kap-toolsbox_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0da136ab3dcf9f4e8817d012af41293f0d082fe3df490fa360eb0f6e1a341d4"
      url "https://github.com/billygate/kap-toolsbox/releases/download/v#{version}/kap-toolsbox_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "855c509859e9e33baf83898d0426a8b33da9e5077bd6b5e3c3df20a4dc16c13e"
      url "https://github.com/billygate/kap-toolsbox/releases/download/v#{version}/kap-toolsbox_linux_arm64.tar.gz"
    end
  end

  name "kap"
  desc "Keyboard-first TUI for Kubernetes contexts and port-forwards"
  homepage "https://github.com/billygate/kap-toolsbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/kap"]
    end
  end

  # No zap stanza required

end
