# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapctl" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "2121f8d1b38545c7cda94c36f01b92aa5c3f4d1b1ff79b488993866e0123aa21"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4f5bc241c214422b484cee777c9dc0958380af77b2ec8a0cc64b533b4ba719e0"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a09acf10ea7a443b4b5d7332c33c4a7e1e0ea21c93dd91a6a5b55ab23a20de69"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5bc56767325bbbee00455bba750ab3da84e993589a145f3a4b06a16596221b6a"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_linux_arm64.tar.gz"
    end
  end

  name "kapctl"
  desc "Keyboard-first TUI for Kubernetes contexts and port-forwards"
  homepage "https://github.com/billygate/kapctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/kapctl"]
    end
  end

  # No zap stanza required

end
