# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapctl" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "5e99c6a00d1da455a4fbebe5f5d297d36eb883f2448f20d955e1918dced74428"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1b3cc55518fd307460c4bff0590648f4d17338d0d9c935cc9072e546c2c5a1e3"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "379a7fcd4d29690335cf32b625b22590427d6d58e5243a68565d09d83bc68dd7"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8fdaf3f90bc2e5ed93b4103bfa259fa829ba32b6bc2cc76dc260ee9ae8b726ee"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_linux_arm64.tar.gz"
    end
  end

  name "kapctl"
  desc "Keyboard-first TUI for Kubernetes contexts and port-forwards"
  homepage "https://github.com/billygate/kapctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/kapctl"]
    end
  end

  # No zap stanza required

end
