# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapctl" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "af8367a52d500c116e4d582e2dda5e8106a0804043aa03a186bb713ae630b749"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7b3f9a1c95124517d17383cdfece52a909cfb77a9ff742ab2267b508d2a47939"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fb4071ebb3141daac8f54133e9b95dad6bda1fb843960f5ac16fc1df7e1d5bb8"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0bdf3c9800c8a974c87aa3cdbf6ca1c5866d6521edaebc553767de267e418c22"
      url "https://github.com/billygate/kapctl/releases/download/v#{version}/kapctl_linux_arm64.tar.gz"
    end
  end

  name "kapctl"
  desc "Keyboard-first TUI for Kubernetes contexts and port-forwards"
  homepage "https://github.com/billygate/kapctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/kapctl"]
    end
  end

  # No zap stanza required

end
