# This file was generated by GoReleaser. DO NOT EDIT.
cask "ripjira" do
  version "0.7.2"

  on_macos do
    on_intel do
      sha256 "97dd14ee2deca15b8d3aaea1ce41f3f461f69fb7ef3eaa5abc4ad7cd4ec8bc7f"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e34221778cb6128905a4066747ecb4f800a92ad8b32c41db585b252b759f5dab"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "17d8d023da06b148b148d5f899326ed3b683effc053ca3a06f4b5aecdf342dfa"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bdbbaba589a07f5ac2ee40633461d9fd3a2ae18e0900d64cc5449834a2f9fe44"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_linux_arm64.tar.gz"
    end
  end

  name "ripjira"
  desc "Jira CLI client with a TUI"
  homepage "https://github.com/billygate/ripjira"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ripjira"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/ripjira"]
    end
    system_command "/bin/ln",
      args: ["-sf", "#{HOMEBREW_PREFIX}/bin/ripjira",
             "#{HOMEBREW_PREFIX}/bin/rj"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/rj"]
  end

  # No zap stanza required

end
