# This file was generated by GoReleaser. DO NOT EDIT.
cask "ripjira" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "1e95c9460c7b6e0be1ee0708788ab76ed183cf45f3a6fbc7594a6336c8af19b8"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8f1b3d088c195635c2c6e746b47be6d698d527324c2cd330009d3c71291b4480"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "69b7c9779d9e78dc13025d5970235446a80d0fe07dd4e947281cec99f5570d7a"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c48c501c0598cbc204c7f560023cfb0bdd6859f46f4875d990d095cc30d658a7"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_linux_arm64.tar.gz"
    end
  end

  name "ripjira"
  desc "Jira CLI client with a TUI"
  homepage "https://github.com/billygate/ripjira"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ripjira"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/ripjira"]
    end
    system_command "/bin/ln",
      args: ["-sf", "#{HOMEBREW_PREFIX}/bin/ripjira",
             "#{HOMEBREW_PREFIX}/bin/rj"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/rj"]
  end

  # No zap stanza required

end
