# This file was generated by GoReleaser. DO NOT EDIT.
cask "ripjira" do
  version "0.9.5"

  on_macos do
    on_intel do
      sha256 "b737e63382ed0e17e2466487b5065668a0a5511ee6ac69449a6b62f4293ae45b"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "15044c801dfbb0519fb57f9447ef30df6b41cdf6903420bfe983989271c5efa7"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "21ef6497d36692ec2de9d835528075d9238f27ddbcc2a59bd9d5bde7962c2d2b"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bd31f6a259019614b90508fc78beeca09573d3d000d48ec9e7687d4e8f9290c6"
      url "https://github.com/billygate/ripjira/releases/download/v#{version}/ripjira_linux_arm64.tar.gz"
    end
  end

  name "ripjira"
  desc "Jira CLI client with a TUI"
  homepage "https://github.com/billygate/ripjira"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ripjira"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/ripjira"]
    end
    system_command "/bin/ln",
      args: ["-sf", "#{HOMEBREW_PREFIX}/bin/ripjira",
             "#{HOMEBREW_PREFIX}/bin/rj"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/rj"]
  end

  # No zap stanza required

end
