# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ripjira < Formula
  desc "Jira CLI client with a TUI"
  homepage "https://github.com/billygate/ripjira"
  version "0.1.0"
  license "PolyForm-Noncommercial-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/billygate/ripjira/releases/download/v0.1.0/ripjira_darwin_x86_64.tar.gz"
      sha256 "486e32c16dfaefd9e58ab3c710b2fef7a45ff3db1f27bb8c9a29fc7a5c3cad96"

      define_method(:install) do
        bin.install "ripjira"
        bin.install_symlink "ripjira" => "rj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/billygate/ripjira/releases/download/v0.1.0/ripjira_darwin_arm64.tar.gz"
      sha256 "7b56aab43970f9e4fa8096ed80153b5bd62861e5743de497736590464514668d"

      define_method(:install) do
        bin.install "ripjira"
        bin.install_symlink "ripjira" => "rj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/billygate/ripjira/releases/download/v0.1.0/ripjira_linux_x86_64.tar.gz"
      sha256 "58596818517a4b9120012935a78c391889bfa2e188ca1104a70a35cdc8edd648"
      define_method(:install) do
        bin.install "ripjira"
        bin.install_symlink "ripjira" => "rj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/billygate/ripjira/releases/download/v0.1.0/ripjira_linux_arm64.tar.gz"
      sha256 "bd7cd5ad77f6e93ecb2537e4998456ef9c14e421c5006711484db38f812e634e"
      define_method(:install) do
        bin.install "ripjira"
        bin.install_symlink "ripjira" => "rj"
      end
    end
  end

  test do
    system "#{bin}/ripjira --version"
  end
end
